# Generated by Django 5.0.1 on 2024-01-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='nameC',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='directors',
            old_name='nameD',
            new_name='name',
        ),
    ]
